name: Gradle Build

permissions: write-all

on: [push, pull_request, merge_group]

jobs:
  build:
    name: Build WorldGuardExtraFlags on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'temurin'

    - name: Grant execute permission to script
      run: chmod +x script.sh

    - name: Update upstream and apply patches
      shell: bash
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "Action Github"
        ./script.sh updateUpstream
        ./script.sh applyPatches

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-read-only: ${{ !(github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/version/')) }}

    - name: Execute Gradle build
      run: |
        cd WorldGuardExtraFlags-Patchs
        mvn -B package --file pom.xml

    - name: Upload WorldGuardExtraFlags jar
      uses: actions/upload-artifact@v4
      with:
        name: WorldGuardExtraFlags-Folia-Snapshot
        path: WorldGuardExtraFlags-Patchs/Spigot/target/WorldGuardExtraFlags.jar*

    - name: Create Release
      if: github.event_name != 'pull_request'
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.tag }}
        name: ${{ env.project_id_b }} - ${{ github.run_number }}
        body: |
          This release is automatically compiled by GitHub Actions
          ### Commit Message
          ${{ env.commit_msg }}
        artifacts: WorldGuardExtraFlags-Patchs/Spigot/target/WorldGuardExtraFlags.jar*
        generateReleaseNotes: true
        prerelease: ${{ env.pre }}
        makeLatest: ${{ env.make_latest }}
        token: ${{ secrets.GITHUB_TOKEN }}
        replacesArtifacts: false

env:
  tag: build-${{ github.ref_name }}-${{ github.run_number }}
  project_id_b: WorldGuardExtraFlags-Folia
  commit_id: ${{ github.sha }}
  commit_msg: ${{ github.event.head_commit.message }}
  pre: false
  make_latest: true